# Generated by Django 4.2.4 on 2023-08-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='Chat',
        ),
    ]
